import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { listPublishedPosts } from "@/lib/blog.server";
import { SITE_URL } from "@/lib/site";
export const revalidate = 300;
export const metadata: Metadata = { title: "Blog | Intorza — Interior Design Business Insights", description: "Expert playbooks on interior design quotation software, GST invoicing in India, and project management.", alternates: { canonical: `${SITE_URL}/blog` }, openGraph: { url: `${SITE_URL}/blog`, type: "website" } };
export default async function BlogPage() { const posts = await listPublishedPosts(); return <div className="min-h-screen bg-background"><Header /><main className="pt-24"><section className="section-padding bg-gradient-hero"><div className="container-custom max-w-4xl text-center"><span className="inline-block text-primary font-semibold text-sm uppercase tracking-wider mb-4">Blog</span><h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold text-foreground mb-6">Insights for <span className="text-gradient">Interior Professionals</span></h1><p className="text-lg md:text-xl text-muted-foreground">Deep, cluster-organised playbooks on quotations, GST invoicing and project management.</p></div></section><section className="section-padding"><div className="container-custom">{posts.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{posts.map((post) => <article key={post.id} className="bg-card rounded-2xl overflow-hidden border border-border hover:shadow-xl transition-all group flex flex-col">{post.cover_image && <img src={post.cover_image} alt={post.title} className="w-full h-48 object-cover" loading="lazy" /> }<div className="p-6 flex flex-col flex-1"><span className="text-[11px] uppercase tracking-wider font-semibold text-primary mb-2">{post.category}</span><Link href={`/blog/${post.slug}`} className="font-display text-lg font-semibold text-foreground mb-3 hover:text-primary">{post.title}</Link><p className="text-muted-foreground text-sm line-clamp-3">{post.excerpt || post.content.slice(0, 150)}</p></div></article>)}</div> : <p className="text-center text-muted-foreground">No blog posts yet. Check back soon!</p>}</div></section></main><Footer /></div>; }
