import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Breadcrumbs, { breadcrumbListSchema } from "@/components/seo/Breadcrumbs";
import { formatBlogContent, formatDate, estimateReadTime } from "@/lib/blog-format";
import { getPostBySlug, listPublishedPosts } from "@/lib/blog.server";
import { SITE_OG_IMAGE, SITE_URL } from "@/lib/site";
export const revalidate = 300;
export async function generateStaticParams() { return (await listPublishedPosts()).map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const { post } = await getPostBySlug(slug); if (!post) return {}; const url = `${SITE_URL}/blog/${slug}`; const description = post.excerpt || post.content.slice(0, 160); return { title: post.title, description, alternates: { canonical: url }, openGraph: { type: "article", title: post.title, description, url, publishedTime: post.created_at, modifiedTime: post.updated_at, images: [post.cover_image || SITE_OG_IMAGE] } }; }
export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const { post, related } = await getPostBySlug(slug); if (!post) notFound(); const url = `${SITE_URL}/blog/${post.slug}`; return <div className="min-h-screen bg-background"><Header /><main className="pt-24"><section className="section-padding bg-gradient-hero"><div className="container-custom max-w-4xl"><Breadcrumbs items={[{ name: "Blog", url: `${SITE_URL}/blog` }, { name: post.title, url }]} className="mb-6" /><Link href="/blog" className="text-primary">← Back to Blog</Link><h1 className="font-display text-3xl md:text-5xl font-bold text-foreground my-6">{post.title}</h1><p className="text-muted-foreground">{formatDate(post.created_at)} · {estimateReadTime(post.content)}</p></div></section>{post.cover_image && <section className="container-custom -mt-8 relative z-10 max-w-4xl"><img src={post.cover_image} alt={post.title} className="w-full max-h-[500px] object-cover rounded-2xl shadow-2xl" /></section>}<section className="py-12 md:py-16"><article className="container-custom max-w-4xl blog-content" dangerouslySetInnerHTML={{ __html: formatBlogContent(post.content) }} /></section>{related.length > 0 && <section className="section-padding bg-muted/30"><div className="container-custom max-w-5xl"><h2 className="font-display text-3xl font-bold mb-8 text-center">Related Articles</h2><div className="grid md:grid-cols-3 gap-8">{related.map((item) => <Link key={item.id} href={`/blog/${item.slug}`} className="bg-card rounded-2xl border border-border p-5 hover:shadow-lg"><h3 className="font-display font-semibold">{item.title}</h3></Link>)}</div></div></section>}</main><Footer /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: post.title, datePublished: post.created_at, dateModified: post.updated_at, mainEntityOfPage: url }) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbListSchema([{ name: "Blog", url: `${SITE_URL}/blog` }, { name: post.title, url }])) }} /></div>; }
