// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rehioexyiybgrxepajnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlaGlvZXh5aXliZ3J4ZXBham5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcyNDg4NjYsImV4cCI6MjA4MjgyNDg2Nn0.sFG1xiZKyIiIVKGMBKRmj0ipZdb20c8KkzaCHmq-hrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});